version: '3'
services:
  frontend:
    build:
      context: ./frontend
    image: frontend
    deploy:
      replicas: 3
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - db
  db:
    image: postgres:11.2
  redis:
    image: redis:5.0.3-alpine