version: '3'
services:
  dev:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:11.2
  redis:
    image: redis:5.0.3-alpine